### ISSUE TITLE
Need to add 'new' keyword to every widget

### ISSUE THREAD

**Issue by SerggioC** [flutter/udacity-course#112]
Can't run example apps because t keeps failing with error "The keyword 'const' or 'new' is required here. Due to an implementation limit, the compiler isn't able to infer 'const' or 'new' here." on every widget...
What's wrong with this?

**Comment by JonathanSum** [comment]
I think it is not perfect yet. However, it works perfect for me by adding the 'new', when the console asks me to add it.

**Comment by SerggioC** [comment]
Yes. It kind of works adding the 'new' keyword everywhere. I'll try to update flutter and dart se of it solves the problem.

**Comment by komuw** [comment]
looks like; https://github.com/flutter/flutter/issues/15590 
and 
https://github.com/dart-lang/sdk/issues/32737

**Comment by maryx** [comment]
What version of Flutter and Android Studio are you using?
`new` and `consts` are not required with Flutter Beta 3.x (such as from [here](https://flutter.io/setup-macos/)), and Android Studio 3.1.x, and the Flutter 24 plugin in Android Studio.

**Comment by Simpler1** [comment]
If using Visual Studio Code, make sure that the following is **NOT** set (under File, Preferences, Settings):

`"dart.previewDart2": false`

**Comment by maryx** [comment]
I'm going to close this issue as Dart 2.0 should allow for optional `new`. If you have trouble, please try updating your setup (see flutter.io/setup for more detail and recommendations). Feel free to open a new issue if there is something else that isn't working!
