### ISSUE TITLE
[dart] The named parameter 'name' isn't defined.

### ISSUE THREAD

**Issue by Simpler1** [flutter/udacity-course#116]
Why does vscode have to be restarted in order to avoid the following three problems:

```
[dart] The named parameter 'name' isn't defined.
[dart] The named parameter 'color' isn't defined.
[dart] The named parameter 'icon' isn't defined.
```
Error displayed:
![image](https://user-images.githubusercontent.com/5922273/40181843-0d37cc2a-59b8-11e8-824b-bafc04de1970.png)

From the starting point of `task_02_category_widget`, I only made the following two changes:
lib\main.dart:
![image](https://user-images.githubusercontent.com/5922273/40181775-e8fbbe7a-59b7-11e8-9849-df17075b75e1.png)

lib\category.dart:
![image](https://user-images.githubusercontent.com/5922273/40181311-d2a8f54e-59b6-11e8-8087-c9d4986f11c6.png)

I haven't found a way to "refresh" vscode to read the updated Category class without closing and restarting vscode.  I spent hours trying to figure out why I was getting these errors and then after shutting down, walking away, and coming back later, it just worked.  I tracked it down to restarting vscode.  There should be a way to force a refresh without having to close and reopen the editor.

Is this a **vscode** problem, a **flutter** problem, or a **dart** problem?

**Comment by Simpler1** [comment]
This problem only occurred on my two Windows machines (Window 10).  My Linux Mint machine did not have this problem.

**Comment by Simpler1** [comment]
And why does Windows create the following three files when I run the app on Android (while Linux does not create these)?

```
android\.project
android\app\.project
android\app\.classpath
```
Are these two issues related?

**Comment by maryx** [comment]
I've noticed this issue with VSCode a few times before in a different codebase, where restarting resolves the analysis issues (though I'm on Linux when this happens). I'm not exactly sure what's causing it - @mjohnsullivan or @devoncarew any ideas?

**Comment by jsoncylu** [comment]
This is happening to me on Android studio for macOS too, any idea why?

**Comment by krishnatandon1208** [comment]
This works fine for me - Android Studios on MacOS. Dart file runs fine. I guess VSCode is not supporting dart. Following for the solution.

**Comment by RonyPixel** [comment]
use flutter clean cache , it might help.

**Comment by WelingtonAlb** [comment]
este erro ocorreu para mim depois que atualizei o flutter para a versão 2.0.2, onde pede envolver o child com um builder (context)

**Comment by domesticmouse** [comment]
Closing this thread out as stale. If y'all are still having issues, please open a new issue. Thanks!
