### ISSUE TITLE
Padding Error

### ISSUE THREAD

**Issue by omarsawalhah** [flutter/udacity-course#122]
I tried to run the code in this repo from the solutions folder for task 02 "solution_02_category_widget", when opening the file in VS Code the following error appears in the "PROBLEMS" terminal tab.

[dart] 1 required argument(s) expected, but 0 found.

And if I run the main.dart I am getting the following error.

flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building Category(dirty):
flutter: No top-level method '' declared.
flutter: Receiver: top-level
flutter: Tried calling: (padding: Instance of 'EdgeInsets', child: Instance of 'Icon')

and here is the "flutter doctor -v" output.
lutter doctor -v
[✓] Flutter (Channel master, v0.5.6-pre.61, on Mac OS X 10.13.5 17F77, locale en-JO)
    • Flutter version 0.5.6-pre.61 at /Users/username/Developer/flutter
    • Framework revision 2e559584e2 (15 hours ago), 2018-06-22 16:32:32 -0700
    • Engine revision 549c855e89
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version openjdk version "1.8.0_152-release"

[✓] VS Code (version 1.24.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.14.0

[✓] Connected devices (1 available)
    • iPhone X • xxxx-xxx-xx-xxx-xxxxx • ios • iOS 11.2 (simulator)

• No issues found!

**Comment by maryx** [comment]
Hi @omarsawalhah! Does VS Code happen to say in which file and line the error is happening? Is there a red squiggly underline in any of the files?

**Comment by omarsawalhah** [comment]
Yes, 
I had to remove flutter and dart plugins and reinstall it again, the problem resolved.

Regards,

**Comment by maryx** [comment]
Sometimes that happens! I'll close this issue for now. Feel free to re-open or file another if an error persists.
