### ISSUE TITLE
Should we close this issues database?

### ISSUE THREAD

**Issue by Hixie** [flutter/udacity-course#125]
cc @maryx @mjohnsullivan 

Do you want to keep this repository's issues database around? Generally we put things in the main flutter/flutter issues list. Either way is fine, I'm just checking on what your desires are.

**Comment by mjohnsullivan** [comment]
We should probably clear out the old/deprecated issues; I'd suggest we keep it open for the moment to catch any lingering edge cases and review closing it down in a couple of months?

**Comment by maryx** [comment]
@Hixie - would you be ok with course-specific issues (e.g. "In exercise 5, when I build, this error pops up...") being posted to flutter/flutter?

I'm not picky either way - I can clean out the existing TODO app issues (we can re-add them if we add more content to the course later) in the meantime.

**Comment by Hixie** [comment]
Yeah, no problem with course-specific issues in flutter/flutter, they're going to end up there anyway.

**Comment by maryx** [comment]
I don't mind closing this repo's issues - @mjohnsullivan when do you think would be the best time to do that? Right now or in a few weeks/months? I defer this to you.

**Comment by Hixie** [comment]
cc @mjohnsullivan any updates?

**Comment by domesticmouse** [comment]
@Hixie Apologies for the delay, I'm happy to maintain this issue tracker going forward. I just updated the code to Flutter 2.5 and added CI.

**Comment by Hixie** [comment]
@domesticmouse Is there a plan for handling the bugs that get filed in flutter/flutter instead?
