### ISSUE TITLE
Your project file contains non-ASCII characters.

### ISSUE THREAD

**Issue by lucashnrique** [flutter/udacity-course#131]
I try to open the project  task_02_category_widget and this error appears:

Your project file contains non-ASCII characters.

![image](https://user-images.githubusercontent.com/42098904/43692281-db23c962-98fc-11e8-98eb-c23252e1e424.png)

How can i fix this?

**Comment by maryx** [comment]
Hi @lucashnrique! Are you able to create/open other Flutter projects?
What about importing the project instead of opening the project (or vice versa)?

**Comment by lucashnrique** [comment]
Thanks, I had not thought of simply opening instead of importing
