### ISSUE TITLE
The Function 'MaterialApp' isn't defined.

### ISSUE THREAD

**Issue by SimonPeter1909** [flutter/udacity-course#133]
![capture](https://user-images.githubusercontent.com/24413796/44630250-0cc1d780-a978-11e8-8334-5aa660c94bf6.JPG)
Hi guys, I have started to learn flutter from a course at udacity.com. 
They have asked to copy the code and paste it into the main.dart file. 
I have done that and I got this Error `The Function 'MaterialApp' isn't defined.` 
I googled that error but it seems to be so hard to find the answer. Can anyone help?

**Comment by Guilherme1886** [comment]
same error here!

**Comment by SimonPeter1909** [comment]
Just go to tools-> flutter -> update flutter... It solved the problem...

**Comment by Guilherme1886** [comment]
Great. I insert new in code and solved the problem. Thanks!

**Comment by matthiassolomon** [comment]
void main() => runApp(HelloRectangle());
then let HelloRectangle extend StatelessWidget. Like this:

class HelloRectangle extends StatelessWidget { .... }

**Comment by Malith97** [comment]
It happens because your flutter SDK and dark SDK is not working properly. you can solve this issues upgrading your flutter sdk. go to the terminal and type

> flutter upgrade --force

after that your fluter sdk and dark sdk will be upgrade, after the installation complete you will be fine.

**Comment by Humboi** [comment]
![Capture](https://user-images.githubusercontent.com/36899938/88730209-7da63700-d12d-11ea-9f02-bc30c7364b1b.PNG)
Please, I need help

**Comment by Humboi** [comment]
![Capture1](https://user-images.githubusercontent.com/36899938/88730346-c78f1d00-d12d-11ea-97ce-a6b0336d234c.PNG)

I have tried several time but not working

**Comment by Malith97** [comment]
Your Flutter SDK and Dart are not working properly. Please update your dart
sdk by typing *flutter upgrade --force* in your terminal
