### ISSUE TITLE
Task 2 Icon Centering Vertically

### ISSUE THREAD

**Issue by heatonandy** [flutter/udacity-course#138]
I really enjoyed the exercise for building out the category_widget in task 2.  

However, one part was frustrating. I spent a good amount of time trying to figure out why my icon wasn't centering vertically in the row (don't regret the churn, I recognize it is an important part of learning).   When I went to the solution code, the final result looked exactly like mine and I was pretty bummed. 

Just an idea to enhance the experience for task 2, get that icon centered vertically so it looks professional when you're done with it.

**Comment by maryx** [comment]
Hi @heatonandy! Thanks for the feedback, and understand your sentiments. If you've figured out a way to center the icons, feel free to make a pull request. Otherwise I'll take a look at some point but I can't give a concrete timeline.

**Comment by cv692001** [comment]
Hey , I am very new to the open source contribution can you Please help me out ;)

**Comment by domesticmouse** [comment]
Hey @cv692001, here's an article on how to [create a Pull Request to a GitHub repo](https://opensource.com/article/19/7/create-pull-request-github). Hope it helps!
