### ISSUE TITLE
A problem about border radius

### ISSUE THREAD

**Issue by Geekiter** [flutter/udacity-course#140]
I creat a inkwell , I want  border radius is round a little when I press it , but it is still square. 
`
     

          child: new Container(
            height: 100.0,
            padding: EdgeInsets.all(8.0),
            decoration: new BoxDecoration(
              borderRadius: new BorderRadius.circular((50.0)),
            ),
            child: new InkWell(
            child: new Row(
              children: <Widget>[
                new Container(
                  padding: EdgeInsets.all(16.0),
                  child: new Icon(
                  Icons.cake,
                  color: Colors.white,
                  size: 60.0,
                ),
                ),
                new Text("Cake", style: new TextStyle(fontSize:24.0, color: Colors.white)),
              ],
              mainAxisAlignment: MainAxisAlignment.center,
            ),
              onTap: () {print("I was tapped!");},
              highlightColor: Colors.redAccent,
              splashColor: Colors.yellow,
          ),

        ),
      ),
    );

`

**Comment by Geekiter** [comment]
I see. InkWell have borderRadius too : )

**Comment by maryx** [comment]
Seems like you've resolved it! I will go ahead and close this issue. Feel free to reopen or open a new issue.
