### ISSUE TITLE
Instructions unclear and possibly wrong

### ISSUE THREAD

**Issue by labermt** [flutter/udacity-course#146]
Instructions state: "Choose the unit_converter project folder, located in this repo at /unit_converter/unit_converter. Select Next for all setup instructions, making sure that the Source Files screen shows Flutter as an option."

However, I never see a "Source Files" screen when installing. Ignoring this, the project doesn't build using Linux.

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "/home/bessermt/tmp/udacity-course/unit_converter/unit_converter/android/gradlew" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools:common:25.3.3.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.pom
       - https://jcenter.bintray.com/com/android/tools/common/25.3.3/common-25.3.3.jar
       - https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.pom
       - https://maven.google.com/com/android/tools/common/25.3.3/common-25.3.3.jar
     Required by:
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.build:manifest-merger:25.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.ddms:ddmlib:25.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.analytics-library:shared:25.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools.analytics-library:tracker:25.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 > com.android.tools.layoutlib:layoutlib-api:25.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 > com.android.tools:dvlib:25.3.3
         project : > com.android.tools.build:gradle:2.3.3 > com.android.tools.build:gradle-core:2.3.3 > com.android.tools.build:builder:2.3.3 > com.android.tools:sdklib:25.3.3 > com.android.tools:repository:25.3.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
  Command: /home/bessermt/tmp/udacity-course/unit_converter/unit_converter/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by maryx** [comment]
Were you able to get this working? If not, please let us know the answer the above^.
I'll close this issue if there isn't a response in the next week or so, after which point feel free to reopen or open a new issue. Thanks!
