### ISSUE TITLE
No TODO's

### ISSUE THREAD

**Issue by labermt** [flutter/udacity-course#147]
Instructions say, "Fill out the TODOs in category.dart and main.dart using the specs below.", however there are no TODO's in the main.dart and category.dart as described in the instructions.

**Comment by maryx** [comment]
Which step are you on?

**Comment by maryx** [comment]
Thanks for your patience!

You'll want to look at the TODOs in the files https://github.com/flutter/udacity-course/blob/master/course/02_category_widget/task_02_category_widget/lib/category.dart and https://github.com/flutter/udacity-course/blob/master/course/02_category_widget/task_02_category_widget/lib/main.dart.

The task and solution are https://github.com/flutter/udacity-course/tree/master/course/02_category_widget

Let me know if this helps - if it resolves your issue, please feel free to close this issue.

**Comment by maryx** [comment]
Closing due to no response.
