### ISSUE TITLE
About dart

### ISSUE THREAD

**Issue by xscs709560271** [flutter/udacity-course#148]
in the cource "03_category_route",the example code is great.but i have few question about how it uesed to do.
like this code clip:
```
const Category({
    Key key,
    @required this.name,
    @required this.color,
    @required this.iconLocation,
  })  : assert(name != null),
        assert(color != null),
        assert(iconLocation != null),
        super(key: key);
```
at first,i was wondered "@required" is a part of grammars,then i find the doc in this [site](https://pub.dartlang.org/documentation/meta/latest/meta/meta-library.html).
i just hope when use the core package section can be subscribed more clearly.thanks.

**Comment by maryx** [comment]
Thanks for your feedback! Feel free to make a pull request if there's a specific explanation you'd like to add to the code comments. Otherwise we can add more commentary to it soon-ish.
