### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by dytra** [flutter/udacity-course#149]
I've just watch the **Build Native Mobile Apps with Flutter** by Udacity and download the sample flutter project
When I ran the command

```bash
flutter packages get
```

It shows some error

```
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because todo depends on cloud_firestore >=0.0.4 <0.3.0 which requires SDK version >=1.8.0 <2.0.0-dev.infinity, version solving failed.
 
pub get failed (1)

```

It seems like the dev haven't updated the dependencies in the `pubspec.yaml`. Please fix it, I wanna do  this project to learn fluter more

**Comment by maryx** [comment]
For the moment, delete the todo project (it's not used in the course). I'll update the code at some point (kinda swamped at the moment). Or feel free to make a PR to resolve the issue :)

**Comment by maryx** [comment]
@dytra what directory/file path are you running `flutter packages get`? 
I tried running it in `udacity-course/course/01_hello_rectangle/solution_01_hello_rectangle` and `udacity-course/unit-converter/unit-converter` with no issues. I got the same issue as you when running it in `udacity-course/todo`, but the course doesn't use the `todo` app currently.

**Comment by maryx** [comment]
We've deleted the todo list code - @dytra please let us know if you're still running into this issue!

**Comment by dytra** [comment]
Oh I thought it used in the course
Perhaps I'm in the wrong address
Thanks for responding anyway
Cheers :wine_glass:
