### ISSUE TITLE
Why should we make CategoryRoute stateful?

### ISSUE THREAD

**Issue by XiminLin** [flutter/udacity-course#154]
Because the only state change in CategoryRoute is initState, which can also be done in the build() method. 

Also, is it good to make stateful widgets as few as possible? I once saw a video saying that making Stateful Widget only if necessary is a good practice. 

Thanks in advance.

**Comment by maryx** [comment]
Hi @XiminLin! Which coding exercise are you currently in? Later on we keep track of more state in this widget (you can see the final version here https://github.com/flutter/udacity-course/blob/master/unit_converter/unit_converter/lib/category_route.dart).

Note that initState() is only called once, while build() is called each time state changes/the UI rebuilds. So sometimes you may only want to call a function once in initState (e.g. to retrieve data from an API - perhaps you don't want to re-retrieve the data each time in build().

You're right, we should use StatefulWidgets only when necessary.

Hope this helps!

**Comment by XiminLin** [comment]
Thank you. I see now.
