### ISSUE TITLE
Opening unit_converter for the quizz

### ISSUE THREAD

**Issue by ReddMonkey2018** [flutter/udacity-course#162]
I can't load up the unit converter. I used the git download code in flutter console and it downloaded fine. I try to import it and it does not seem to find out it's a flutter app. If I just open it, it's full of errors... What am I doing wrong?

**Comment by drtoio** [comment]
Same. When i want to import Task02, it just open it as dart, not as a flutter project, so i can't use it.

**Comment by maryx** [comment]
Hi @ReddMonkey2018 and @drtoio, can you verify that you're importing using Android Studio, and that you have the Flutter plugin installed?
Please also add the output of running `flutter doctor`.

Here's what should happen:
When you go to New->Import Project..., you should be taken to a screen like this:

<img width="916" alt="Screen Shot 2019-05-03 at 10 14 04 AM" src="https://user-images.githubusercontent.com/3357543/57153862-385d5300-6d8c-11e9-8c17-11a065fffeaa.png">

Then select Next, and Next, and then you should see this:
<img width="907" alt="Screen Shot 2019-05-03 at 10 14 44 AM" src="https://user-images.githubusercontent.com/3357543/57153926-5cb92f80-6d8c-11e9-9f5b-3663c70ce517.png">

Select the Flutter project.

After the project opens, make sure to clock on the `Get dependencies` link at the top right.

**Comment by ReddMonkey2018** [comment]
Yeah I don't have the last screen coming up...

**Comment by maryx** [comment]
What's the output of `flutter doctor`?
What if you try opening a project rather than importing it?

**Comment by ReddMonkey2018** [comment]
I get error messages if I try to open it.

And flutter doctor does not seem to pick up any error..

I can start a project from scratch and it works fine. Just not importing

**Comment by maryx** [comment]
It would help to post the output of flutter doctor so I can see if I can replicate the issue.

Can you also post the error messages? That would help in debugging the issue too.

Can you go into the project's lib/ directory and do a `flutter run` to see if the project builds and runs from the command line?

**Comment by domesticmouse** [comment]
Closing out this thread as stale. If y'all are still having issues, please feel free to open a new issue. Thanks!
