### ISSUE TITLE
Category name not used in ConverterRoute

### ISSUE THREAD

**Issue by pablolaurin** [flutter/udacity-course#164]
https://github.com/flutter/udacity-course/blob/56d93305409fba4f19905d26792148cbcf67e7d7/course/04_navigation/solution_04_navigation/lib/converter_route.dart#L28

Why is the category name passed to ConverterRoute? Is not used inside this widget.

**Comment by maryx** [comment]
You are right. It's possibly leftover from one of the past versions of the UX where the name was shown on the screen. Feel free to make a PR to remove it, otherwise I will probably make one in the next week or so.
