### ISSUE TITLE
Code doesn't follow modern Dart standards

### ISSUE THREAD

**Issue by jammymalina** [flutter/udacity-course#168]
Hi everyone, 

Nice job on the course. I was just playing around and I noticed the modern coding standards are not followed, e.g. there are lot of for loops where map would be more suitable. It would be quite nice if you refactored the code in the future to teach the beginners modern coding practices.

**Comment by maryx** [comment]
Thanks @jammymalina for the feedback!
Everyone - feel free to make PRs for this in the meantime. I'll get to it at some point.

**Comment by domesticmouse** [comment]
I've updated the codebase for Flutter 2.5 and `flutter_lints` compliance. As an amusing aside, the `flutter_lints` bundle of lints includes a rule that prefers for loops over maps for ease of readability, so theres that.
