### ISSUE TITLE
Code is full of errors and deprecated libraries and functions

### ISSUE THREAD

**Issue by govindpathak4297** [flutter/udacity-course#178]
I try to copy and paste the code but there are a lots of errors .
 Being a beginner in flutter I don't even know how to solve these errors

**Comment by domesticmouse** [comment]
@RedBrogdon what should we do with this repo?

**Comment by wlaughto** [comment]
There is a fairly simple solution to the OPs problem. Use the attached pubspec_update.txt file to update all the pubspec.yaml files in the solutions. Hit 'Get pub' or 'Get Dependencies' and most of the problem errors will be resolved. There will probably still be issues with deprecated code etc, but these are ignored, although can be fixed if you want to follow the instructions. I didn't as the app still runs without it being done.

[pubspec_update.txt](https://github.com/flutter/udacity-course/files/6080591/pubspec_update.txt)

**Comment by domesticmouse** [comment]
As far as I can tell we have two options here. The first option is to archive this project to reflect that it is currently unmaintained. The second option is to update it, and add in CI with daily checks against stable/beta/dev. The downside of the second approach is that this codebase will drift away from the code showcased in the Udacity course.

@wlaughto feel free to raise your changes as a PR to this repo, as that would help push more towards the latter than the former decision ;-)

**Comment by corelioj** [comment]
I am a begginer too. I´ve made the changes in the pubspec.yaml and still have problems on APP running in the cellphone. I there anything else there I must execute?
