### ISSUE TITLE
Can't find the course.

### ISSUE THREAD

**Issue by Nicholaistp** [flutter/udacity-course#83]
Is this course still in development or a section of another course because I can't find it on Udacity.

**Comment by Kartik1607** [comment]
Most probably will be available in future.

**Comment by maryx** [comment]
It's still in progress! :) I'll update this when the course is released.

**Comment by maryx** [comment]
The course, Build native mobile apps with Flutter, is now located at https://www.udacity.com/course/ud905 :)
