### ISSUE TITLE
new prefix

### ISSUE THREAD

**Issue by ZaynJarvis** [flutter/udacity-course#96]
Hi! I discover that there is no new prefix and const for color, which leads to some errors in my version of flutter.
Which version of flutter or dart should I use to get rid of new?

and just hope that u will have a firebase sample code, the sample code I get from elsewhere were already out of date...

Thank you!!!! for helping!!! I just start fluttering recently..

**Comment by maryx** [comment]
With the newest Flutter SDK (anything higher than 0.3.x, which you can install from .zip here: https://flutter.io/get-started/install/), you should be able to now build the course code in Dart 2.0, without the `new` and `const`.
Remember to run a `flutter upgrade` and update dependencies in your IDE if necessary. The red error messages/underlines may show up initially, but after the first successful build, should disappear.

Please let me know how it goes @ZaynJarvis!

**Comment by maryx** [comment]
The README for this repo has also been updated.

**Comment by ZaynJarvis** [comment]
Thank you!

**Comment by maryx** [comment]
Closing now. Please re-open if you still encounter the same problem. Thanks!
